### ISSUE TITLE
Compiling on 32 bit machines

### ISSUE THREAD

**Issue by pietercolpaert** [rdfhdt/hdt-cpp#1]
https://github.com/rdfhdt/hdt-cpp/blob/master/hdt-lib/src/util/bitutil.h#L42

This gives problems as it is already defined on a 32 bit machine.

**Comment by bendiken** [comment]
Do you mean that an overloading problem arises when `size_t` equals `uint32_t`? I don't have a 32-bit host available to test this on right now, but that seems like the likeliest analysis from the function you point to.

**Comment by bendiken** [comment]
Since the `wordSelect1(uint32_t, uint32_t)` and `wordSelect1(uint64_t, uint64_t)` overloads are not actually used as such anywhere in the code base, I've simply commented them out for now. That should resolve this issue on 32-bit hosts.

The only overload that is actually needed is `wordSelect1(size_t, uint32_t)`, used in https://github.com/rdfhdt/hdt-cpp/blob/master/hdt-lib/src/bitsequence/BitSequence375.cpp#L380. As used from that call site, there was a potential issue with integer type promotion due to the inconsistent smaller type of the second argument which I've resolved by making the second parameter consistent with the first parameter, as per the other `wordSelect1` overloads.
