### ISSUE TITLE
Unicode sequences are incorrectly escaped

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfhdt/hdt-cpp#11]
This triple:
`<http://dbpedia.org/resource/Barack_Obama> <http://www.w3.org/2002/07/owl#sameAs> <http://el.dbpedia.org/resource/\u039C\u03C0\u03B1\u03C1\u03AC\u03BA_\u039F\u03BC\u03C0\u03AC\u03BC\u03B1> .`
results in 
`<http://dbpedia.org/resource/Barack_Obama> <http://www.w3.org/2002/07/owl#sameAs> <http://el.dbpedia.org/resource/\\u039C\\u03C0\\u03B1\\u03C1\\u03AC\\u03BA_\\u039F\\u03BC\\u03C0\\u03AC\\u03BC\\u03B1>.`
This is particularly a problem when using HDT via LDF, as the n3 parser throws an exception.

**Comment by RubenVerborgh** [comment]
Did you compile the latest `develop` branch and the `SERD` option in the Makefile, and then create the HDT file with `-f turtle`? The SERD parser correctly parses unicode.

**Comment by RubenVerborgh** [comment]
Note that I patched the server for this in https://github.com/LinkedDataFragments/Server.js/commit/f95a315b3186b2438969facb0849cbf54df823e6 (which is in v1.1.3), which I later had to revert in https://github.com/LinkedDataFragments/Server.js/commit/2041b4e1eb1406488e377aae242fe014850a473b. It was reverted because there was no reliable way to determine whether an HDT file was correctly encoded or not; as such, we had to assume correctness.

**Comment by LaurensRietveld** [comment]
Ah, that was the fix indeed. thanks!
