### ISSUE TITLE
master / develop

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfhdt/hdt-cpp#116]
I noticed that the master is currently at a non-tagged commit, whereas we had discussed to keep master at the latest version (v1.2.0 now) and to development at develop.

Even worse, master and develop have diverged…

I think we should:
- pay attention to always accept PRs to develop (we should likely protect master in the settings)
- revert the commits on master, and replay them on develop

Feedback welcome!

**Comment by rubensworks** [comment]
Just my two cents:

For projects that regularly receive PRs, I've noticed that it may be easier to make master the development branch, due to this being GitHub's default PR target (although this can be changed when changing the default branch). A separate stable branch would then contain the latest release and progress with patches.

**Comment by sharpaper** [comment]
My 2 cents:

- use master as default dev branch
- develop new features in a new separate branch (one branch per feature). When a feature is ready, merge the branch into master and remove branch
- when master is good/stable enough, tag a new release `v1.0`, `v1.2`, etc

**Comment by mielvds** [comment]
I agree with @sharpaper. This approach is getting more common, and tags/releases can serve as "release/stale branch"

**Comment by LaurensRietveld** [comment]
I'm afraid of feature branches ending up out-of-sync and unused if we follow this approach too rigidly. I understand that for things like the long-dict-id feature we need a separate branch. Most features are pretty small though and can easily be merged to dev (after all, it's a development branch, it is allowed to break). On dev these feature actually get tested (example: the autotools improvement), where on feature branches they often won't. 

> develop new features in a new separate branch (one branch per feature). When a feature is ready, merge the branch into master and remove branch

Not sure what you mean by 'ready'. Do you expect a workflow where people test each others feature branches? Most HDT-related repo's show that that simply doesn't happen.

I.e., Not claiming that there is no problem, but I'm all up for a pragmatic approach here.

ps. wrt to the actual problem addressed by Ruben (the diverged master/dev branches): agreed that master should be protected. Don't want to diverge both branches

**Comment by LaurensRietveld** [comment]
I fixed the divergion issue by removing some commits on master (and moving them to develop where needed). The master branch is protected now as well, so this shouldn't happen again soon

**Comment by joernhees** [comment]
Sorry if i did something wrong, but actually: take me as an example. I simply assumed that this repo is similar to nearly all others on github (basically as @sharper described [above](https://github.com/rdfhdt/hdt-cpp/issues/116#issuecomment-338379264)).

There's no benefit of having a "jumping master": If you're searching for the latest release all you have to do is open the release page https://github.com/rdfhdt/hdt-cpp/releases or type `git tag -l`.

As @rubensworks, @sharpaper and @mielvds, i also would advise to just use the default, as it's very beneficial: the community rule that master is the main dev branch but with the addition that it should "work" allows for easy contribution, and merging. It also implies that when developing a complicated new feature that touches a lot of things, you can do so in a branch and regularly merge master (the only branch you need to know about) into that branch to incorporate smaller contributions. Once done, this drastically reduces maintainer efforts a lot... And last but not least: it doesn't need special documentation and understanding of every contributor!

Another thing that is actually maybe even more important: please never rebase online master... we now have docker automated builds for images from commits that do not exist anymore. Following the Dockerfile source link will lead to a not existing file on the master branch. Everyone trying to check the source will think we did something evil...

**Comment by LaurensRietveld** [comment]
I'm fine with changing the default branch to develop (probably is a low impact action anyway). But if I understand you correctly, you want to switch dev and master as well. What actual problems we had in the last year does this solve? This just sounds like something that only creates an overhead for people who currently have a cloned repo, without there being a clear benefit (other than 'conformance with other libs', though even that is debatable).

About the rebase/reset: sorry if this created problems for you. This were only files unrelated to the c++ code though. Luckily, with a protected branch, this should never happen again anyway

**Comment by wouterbeek** [comment]
Is the only benefit of changing the use of `master` from release publishing to development that this is more in line with what other projects currently do?  That seems to be a pretty minor benefit to me.

A much more important issue we have is that feature branches are almost never merged into the main branch (be it `master` or `develop`).  As a result, potentially valuable contributions are not being picked up.  A solution to that problem would be truly valuable.

**Comment by joernhees** [comment]
Hmm, I don't exactly see myself as a noob dev on github, but i was confused and ended up doing something wrong. I'm not sure everyone in your core team actually knew that it's not allowed to push to master, but ok, you now protected it and it can't happen again.

The sole reason why i reply and continue here is cause i don't think that it's the best approach when you have to protect the project from newcomers following default community conventions.

> Is the only benefit of changing the use of `master` from release publishing to development that this is more in line with what other projects currently do? That seems to be a pretty minor benefit to me.

You're right, it doesn't really matter how branches are called. However, for potential new contributors reducing the amount of WTFs/min (http://commadot.com/wtf-per-minute/) is actually a crucial aspect. What i'm saying here (and others seem to agree) is that by not following the default convention on github, we're putting unnecessary hurdles in the way of newcomers.

What you set up with jumpy `master` and `develop` branch is known as "git flow". It is however not the default community convention on github, which is fittingly called "github flow": https://lucamezzalira.com/2014/03/10/git-flow-vs-github-flow/

I've seen projects where "git flow" made sense, but that's usually in companies where tons of dev teams work on the same product and keep that alive in different versions for tons of customers. There are only few (and typically very big) open source projects that actually use (something like) git flow, and where i think the overhead is justified. If you do not have hotfixes and regular releases and a very large developer base and a very active (mostly paid only for that) maintainer keeping it all together, then "github flow" simply reduces overhead and is easier. I guess that's why the majority of projects on github use it.

All of that said, i think there are two options here:
- *proceed with git flow*: In that case i'd recommend to document it clearly and prominently (in the README for example) and to make `develop` the default branch in the project settings. Otherwise https://github.com/rdfhdt/hdt-cpp shows master and has a tendency to look abandoned in between releases.
- *use github flow*: In that case just fast-forward merge `develop` into `master`, then delete the online `develop` branch. The majority of people will not be confused by this, but actually expect this, as long as the current `develop` branch is meant to actually "work". If they're on the develop branch, they'll notice on a fetch that master overtook them. If they were using hdt-cpp as a lib, the correct thing would've been to checkout a tag or actually downloading a release tarball as it doesn't contain the full history and is smaller.

The issue of people not merging branches back is IMO pretty independent of git/github flow.

**Comment by sharpaper** [comment]
Using any branch is OK, as long as it's clear which one contributors are supposed to use. Right now it's not clear from the README what is the distinction between master and develop, so it's natural that contributors will submit PRs to master and completely ignore develop.

**Comment by LaurensRietveld** [comment]
As I haven't seen anybody objecting to changing the default branch, I've updated it to be `develop`. 
The `README.md` now also reflects the branch structure (PR #123) , so that's great. 
Thanks for the discussion, I think we managed to solve most of the pain points here. I'll try to close this issue again ;)
