### ISSUE TITLE
rdf2hdt: add option to treat bad triples as a "warning" instead of an "error"

### ISSUE THREAD

**Issue by sharpaper** [rdfhdt/hdt-cpp#117]
Right now when converting for example a `.nt` file to `.hdt`, rdf2hdt [throws an error](https://github.com/rdfhdt/hdt-cpp/blob/a0dc035b3bf5c91b602e12f0e5c0309ca4d5bde0/hdt-lib/src/hdt/BasicHDT.cpp#L268) if a triple is considered invalid, and the entire process stops.

Would it be possible to add an option to treat invalid triples as warnings instead of errors? In some cases, if a `s p o` triple is invalid for whatever reason, I'd just like to move forward and not pay much attention to it.

**Comment by wouterbeek** [comment]
> If a `s p o` triple is invalid for whatever reason, I'd just like to move forward and not pay much attention to it.

HDT is technically able to store non-RDF formats that happen to consist of statements that are sequences of three terms.  It may be a good idea to make clear to consumers of the HDT file that the file does not contain RDF.  Maybe a header property?

**Comment by sharpaper** [comment]
Sorry @wouterbeek I'm a bit confused by your answer. What I was trying to say is, that if my `.nt` has an invalid triple, I'd like to tell `rdf2hdt` to skip/ignore it instead of aborting the whole conversion.

**Comment by wouterbeek** [comment]
@sharpaper Sorry for the confusion, I misunderstood your phrase "if a triple is invalid, I just like to move forward".  I interpreted that as you wanting to generate HDT files that store triples that are not RDF triples (but some other triple format, e.g., CSV files that have three columns).

What you actually mean is that the Serd parser could use some clever heuristics in order to extract RDF from a non-RDF source file, and construct an HDT for the thus extracted RDF.  This feature is discussed in [this Serd issue](https://github.com/drobilla/serd/issues/7), and already works for simple, line-based serialization formats.  It is quite difficult, but possible, to extend this support to other formats (Turtle, TriG) as well.

Notice that it is not possible to skip all and/or only buggy triples, because triples are themselves defined in terms of valid syntax.  The only thing that you can do when you encounter something that is not a triples, is jumping forward to a part of the input stream that looks OK and that may contain triples moving forward.

**Comment by wouterbeek** [comment]
@sharpaper Can you use the Serd feature that I mentioned in my previous post?  If so, then this issue can be closed.

**Comment by sharpaper** [comment]
Hi @wouterbeek,

I'm not sure how to go about trying out different serd features, but reading the other thread it looks like a complex topic, especially considering complex syntaxes such as ttl or trig. BTW I didn't mean that rdf2hdt should be able to parse any malformed input stream. But for example I've encountered a turtle file with this triple

```
<http://example.org/Subject>
    ex:name "Name" ;
    ex:homepage <> .
```

Here rdf2hdt fails because of the missing URI, with `ERROR: Could not convert triple to IDS!`. What I meant is simply an option to skip these simply cases, and not deal with a heavily broken input stream.
On the other hand... I do think it's better to have a separate tool to clean data **before** feeding it to rdf2hdt. So I think a better option is to add in the documentation that rdf2hdt expects a valid input, and that any RDF file should first be piped through some other tool (such as RIOT or anything else you want to provide) to clean/validate data before it's converted to HDT.

**Comment by wouterbeek** [comment]
The distinction between simple and heavily broken input data makes sense intuitively, but you have not defined it in such a way that it can be implemented.  One approach would be to define this difference in terms of edit distance (i.e., the minimal number character deletes and inserts that is needed in order to get to correct RDF).  In your example the edit distance to correct RDF is 3, for example:

```turtle
<http://example.org/Subject>
    ex:name "Name" .
#    ex:homepage <> .
```

There are other 3-edit distance solutions though:

```turtle
#<http://example.org/Subject>
#   ex:name "Name" ;
#    ex:homepage <> .
```

So we should prefer minimum edit distance candidates that result in more triples.  The following is a 3-edit distance candidate that results in more triples:

```turtle
<http://example.org/Subject>
    ex:name "Name" ;
    ex:homepage <x:x> .
```

But this has introduced a term `x:x` that is not in the source data.  So the character add operations should be restricted to syntactic elements (rather than content).  Is that a proper definition of the intuition you expressed?  Am I missing something?

**Comment by RubenVerborgh** [comment]
I'm opposed to this idea. Invalid input should be rejected; who knows what we end up with otherwise.

**Comment by wouterbeek** [comment]
@RubenVerborgh We know what we end up with: a LOD Cloud full of dirty data, and the onus of producing correct RDF is shifted to the client :)

**Comment by sharpaper** [comment]
I agree with @RubenVerborgh that invalid input should be rejected. There should exist only a handful of tools to validate or clean data, otherwise every single project would have to create its own cleaning/validation library from scratch. So, an input like this

```
something very non-RDF .
<x:x><x:x><x:x> .
yet some more non-RDF
```

I think can be rejected entirely. The issue I was trying to raise is different. Take for example the scenario of somebody converting a SQL database into a Turtle file. They create a Turtle file like this

```

**Comment by RubenVerborgh** [comment]
The `<>` case is a missing base URI, that's something else.

**Comment by sharpaper** [comment]
> The `<>` case is a missing base URI, that's something else.

But rdf2hdt still throws an error, regardless of the `-B` flag.

**Comment by sharpaper** [comment]
Another example of "bad URI" would be a .nt file with a relative URI rather than absolute.

**Comment by RubenVerborgh** [comment]
> But rdf2hdt still throws an error, regardless of the -B flag.

That's a bug then; the base URI setting isn't passed to SERD.

> Another example of "bad URI" would be a .nt file with a relative URI rather than absolute.

Faulty file, which we should not parse.

**Comment by sharpaper** [comment]
OK so I think this issue is fixed now that the README contains a warning about clearing data **before** using HDT tools.

I'll live this open though for the issue with the `-B` flag.

**Comment by mielvds** [comment]
Can you rename it then? Or create a new one?

**Comment by sharpaper** [comment]
OK, [moved](https://github.com/rdfhdt/hdt-cpp/issues/131).
