### ISSUE TITLE
Always store XSD strings in one and the same way

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#173]
As @larsgsvensson noticed, it is unfortunate that the same XSD string literal can be stored in two ways.  It would be best if upon HDT creation, the syntax `"..."^^<http://www.w3.org/2001/XMLSchema#string>` was always used, and the syntax `"..."` was never used.

Currently, queries for XSD string are needlessly complex, since this must query for two forms and must integrate results on the fly.  Also, this allows duplicate terms and duplicate triples to be stored in one HDT, so results are no longer guaranteed to be be unique and counts are no longer guaranteed to be correct.

Unfortunately, `"..."` is a legal RDF term in Turtle, TriG, N-Triples, and N-Quads. This means that any compliant parser is allowed to emit `"..."`, and that this should not be fixed in the parser (i..e, Serd).

Instead, what is needed is HDT-specific code that transforms `"..."` into `"..."^^<http://www.w3.org/2001/XMLSchema#string>` upon HDT file creation. If somebody would be able to implement this in a pull request, then this would be very welcome.

(Notice that this would not invalidate existing HDTs that use `"..."`. It would just guarantee that newly created HDTs are not ambiguous.)

**Comment by larsgsvensson** [comment]
@wouterbeek 
> Instead, what is needed is HDT-specific code that transforms `"..."` into `"..."^^<http://www.w3.org/2001/XMLSchema#>` upon HDT file creation. If somebody would be able to implement this in a pull request, then this would be very welcome.

Perhaps it would be better to do it the other way round, i. e. that the HDT-specific code transforms `"..."^^<http://www.w3.org/2001/XMLSchema#>` to `"..."` when creating the file, since the use of `"..."^^<http://www.w3.org/2001/XMLSchema#>` seems to cause problems with e. g. the Jena `NodeDictionary`.

**Comment by larsgsvensson** [comment]
And probably it would be necessary to update the [hdt spec](http://www.rdfhdt.org/hdt-internals/#triples) to make the format non-ambiguous in this respect.

**Comment by mielvds** [comment]
You mean `"..."^^<http://www.w3.org/2001/XMLSchema#string>` right?

**Comment by mielvds** [comment]
Also note that if a language tag is present, the type should be `http://www.w3.org/1999/02/22-rdf-syntax-ns#langString`

**Comment by larsgsvensson** [comment]
@mielvds scriptit:
> You mean``` "..."^^<http://www.w3.org/2001/XMLSchema#string>``` right?

Yes.

> Also note that if a language tag is present, the type should be ```http://www.w3.org/1999/02/22-rdf-syntax-ns#langString```

Right.

**Comment by mielvds** [comment]
> @mielvds I may misinterpret your remark about rdf:langString, please CMIIW. In RDF standardization it was chosen to not encoded language tags as part of the lexical form. 

correct.

> This means that the language tag must be stored somewhere outside of the lexical form, which results in literals having three distinct components: (1) lexical form, (2) language tag, (3) datatype IRI. 
Since the language tag only appears for literals whose datatype IRI is rdf:langString, the language tag is often stored instead of the datatype IRI. 

Yes. I just wanted to point out that if you convert every `"..."` to  `"..."^^<http://www.w3.org/2001/XMLSchema#string>`, you have to make sure they have no language tag. 

> HDT follows the Turtle/N-Triples/N-Quads/TriG serializations in this respect.

So this magic happens in the dictionary and AFAIK literals are just encoded as the complete value. Except for knowing where the literal is, HDT does not check whether the literal has a language tag, a datatype or both.

I can start a PR on this.

PS: why are you not mentioning the `#string`at the end? Just wanting to make sure I'm nog missing anything...

**Comment by wouterbeek** [comment]
@mielvds It would be great if you could start a PR on this!  My C++ is not good enough yet :-(

Indeed, I forgot `string` in some locations; fixed that now.

**Comment by wouterbeek** [comment]
@mielvds Thanks for fixing this!
