### ISSUE TITLE
tips for processing RDF dumps

### ISSUE THREAD

**Issue by m1ci** [rdfhdt/hdt-cpp#176]
Dear all,

we are dealing with quite large RDF dumps (6GB of compressed RDF/Ntriples in .bz2).

I have several questions around this?

1) Can I directly create HDT out of .bz2 compressed RDF/NTriples?

2) What are the computational requirements for compressing such large RDF dumps into HDT?

Thanks!

**Comment by wouterbeek** [comment]
Hi @m1ci , GNU zipped input works for sure, I don't know about Bzip2.  Since I do not know the data you are converting, I can only give some rough estimates.  Let me know what your observed metrics were, that way I can check how accurate / inaccurate my predictions are :-)

Since you have 6GB of compressed N-Triples, your dataset consists of 0.5B triples.  Your resulting HDT file will be 17GB in size, and you will need 68GB of RAM in order to build it.  The creation of the HDT file will take 2.5 hours.

**Comment by m1ci** [comment]
Hi @wouterbeek, thanks for the detailed info!
In fact, this 6GB compressed .bz2 file (http://downloads.dbpedia.org/2016-10/core-i18n/en/nif_text_links_en.ttl.bz2) about 928M triples. Do you think we need then around 100GB of RAM an it will take like 5 hours?

**Comment by wouterbeek** [comment]
Yes, probably.  I underestimated the ability of Bzip2 to compress better than GNU zip.  Let me know how it works out.

**Comment by wouterbeek** [comment]
Closing this one since the question seems to be answered sufficiently (estimating the amount of memory usage ahead of time remains difficult, because it depends on the specifics of the transformed dataset).
