### ISSUE TITLE
Error with mapHDT ... Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by ahmad88me** [rdfhdt/hdt-cpp#191]
I got the below error.
```
Undefined symbols for architecture x86_64:
  "hdt::HDTManager::mapHDT(char const*, hdt::ProgressListener*)", referenced from:
      store_num_cols(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in filter_num.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I've also tried the example on the webpage, it didn't work. 
Can someone please help (I am running it on macOS High Sierra).

Cheers,

**Comment by ptorrestr** [comment]
It looks like some of the objects were not built properly. Do you compile `libhdt` yourself? If you do so, was the compilation successful?

Could you please include the file that is producing the error.

**Comment by ptorrestr** [comment]
You need to include a reference in your makefile to `libhdt`.

When creating the binary file, you need to include `-lhdt` in the compilation line (line 26). 

Make sure you have `libhdt` installed in the standard directory, otherwise, you will also need to set the path where `libhdt` is installed (e.g. `-L/my/path/to/libhdt -lhdt`)

**Comment by ahmad88me** [comment]
@ptorrestr Thank you, it works 👍
