### ISSUE TITLE
Triple estimation does not work

### ISSUE THREAD

**Issue by wouterbeek** [rdfhdt/hdt-cpp#199]
Triple estimations does not work for me.  I'm quite sure this used to work, so I'm probably making a stupid mistake.  When I compile the following code:

```cpp
#include <HDT.hpp>
#include <HDTManager.hpp>
#include <iostream>

int main() {
  hdt::HDT* hdt = hdt::HDTManager::mapHDT("sample.hdt");
  hdt::IteratorTripleString* it = hdt->search("","x:x","");
  size_t est {it->estimatedNumResults()};
  size_t n {0};
  while (it->hasNext()) {
    it->next();
    n++;
  }
  delete it;
  std::cout << "Estimate: " << est << '\n'
            << "Iterations: " << n << std::endl;
  return 0;
}
```

and then run it over the HDT file generated for the following Turtle:

```ttl
<x:x> <x:x> <x:x>.
<x:x> <x:y> <x:x>.
<x:x> <x:y> <x:x>.
<x:x> <x:z> <x:x>.
<x:x> <x:z> <x:x>.
<x:x> <x:z> <x:x>.
<x:x> <x:a> <x:x>.
<x:x> <x:b> <x:x>.
<x:x> <x:c> <x:x>.
<x:x> <x:d> <x:x>.
```

I get:

```
Estimate: 7
Iterations: 1
```

I'm expecting these number to be identical :-(

**Comment by dinikolop** [comment]
Hi, Wouter! If you call method `hdt::HDTManager::mapIndexedHDT("sample.hdt")` instead of `hdt::HDTManager::mapHDT("sample.hdt")`, then you will not have this problem. This, of course, will create the index file.

The source of this issue lies within the implementation of the `estimateNumResults` of the particular iterator class for this case: applying a `? P ?` query upon a non-indexed HDT. In this case your `hdt::IteratorTripleString *it` will be instantiated as a subclass pointer `hdt::IteratorY *`, an iterator class that is more efficient for `? P ?` queries. In the [implementation of the `estimateNumResults`](https://github.com/rdfhdt/hdt-cpp/blob/develop/libhdt/src/triples/BitmapTriplesIterators.cpp#L682), the iterator returns as estimation the number of all triples. I am not sure why it is like that, but I can investigate how to change it.

In the case of calling mapIndexedHDT, the iterator for `? P ?` queries will be instantiated as `MiddleWaveletIterator` which I believe returns an accurate number of results when calling [`estimateNumResults`](https://github.com/rdfhdt/hdt-cpp/blob/develop/libhdt/src/triples/BitmapTriplesIterators.cpp#L485).

**Comment by wouterbeek** [comment]
Thanks!  I was indeed opening the HDT file in an incorrect way.
