### ISSUE TITLE
Arbitrary estimated number of results

### ISSUE THREAD

**Issue by immortaleeb** [rdfhdt/hdt-cpp#27]
I generated a dataset of about 1M triples using the watdiv data generator and converted the resulting file using HDT.
When querying for certain triples, it seems like some estimated counts are not very "estimated", but rather arbitrary.

For example: there should be 433615 triples with the predicate ``http://db.uwaterloo.ca/~galuc/wsdbm/friendOf`` but when executing the query ``?v0 http://db.uwaterloo.ca/~galuc/wsdbm/friendOf ?v2`` I get an estimated count of 3878 triples, which is quite an order of magnitude different.

In order to get these estimated counts, `IteratorTripleID. estimatedNumResults()` is used (see https://github.com/RubenVerborgh/HDT-Node/blob/master/lib/HdtDocument.cc#L139).

You can find the hdt file I'm using to test querying here: https://dl.dropboxusercontent.com/u/16059961/watdiv_10_dataset.zip

**Comment by mielvds** [comment]
@RubenVerborgh @rdfhdt/commiters any experience with this?

**Comment by RubenVerborgh** [comment]
Estimates with predicates are known to be _very_ approximate.

**Comment by mielvds** [comment]
Like I thought, just didn't know it was this bad.

**Comment by webdata** [comment]
I found a bug in the code producing this arbitrary estimation. It should be fixed now in the last commit 36128a7ecd10d1eba7c8db4c502da731f0cc17c3. Please delete your old .index file and generate it again. Let us know if you experimented further issues in order to close this issue.

(long explanation: In .index we included the number of triples per predicate but we had a bug in the computation of this number. In addition, this number was not used to estimate the query result.)

**Comment by RubenVerborgh** [comment]
@immortaleeb @mielvds Does @webdata's commit address your issue?

**Comment by mielvds** [comment]
?Thanks a lot @webdata! Does it help @immortaleeb?

________________________________

**Comment by immortaleeb** [comment]
From what I can tell it does seem to solve the problem, thanks @webdata !

**Comment by RubenVerborgh** [comment]
@webdata Is it possible that some estimates have become less accurate now? See test failures at https://travis-ci.org/RubenVerborgh/HDT-Node/jobs/140673068. Problems occur exclusively for the `?s <p> ?o` pattern.

**Comment by RubenVerborgh** [comment]
Haha, no, it's actually the opposite: my tests included the inaccurate numbers because this used to be the result. [Changed the tests](https://github.com/RubenVerborgh/HDT-Node/commit/0f35a8ce30a976e4910319ed070caa6a0d97e090#diff-5e57734ee1c5198982331537ee854c91L316) to include the accurate numbers.
