### ISSUE TITLE
Update website to point at GitHub, instead of Google Code

### ISSUE THREAD

**Issue by CristianCantoro** [rdfhdt/hdt-cpp#3]
Hello,

Basically every url mentioned in the [rdfhdt.org](http://www.rdfhdt.org/) website points to the [Google code project  page](https://code.google.com/p/hdt-it/), but it seems to me that the latest developments are happening here. So I think which is the official/main repo for the project should be clarified.

Thanks,

Cristian

**Comment by bendiken** [comment]
By now, of course, Google Code has been retired and archived by Google, leaving GitHub the de-facto official location no matter what the copy on [rdfhdt.org](http://www.rdfhdt.org/manual-of-the-c-hdt-library/) still erroneously claims.

For the record, from a quick look the SVN and Git revision histories diverged after [r390](https://code.google.com/p/hdt-it/source/detail?r=390) in SVN, but the Google Code project only has two further commits since then and those fixes have presumably been incorporated into the Git lineage as well in some form.

**Comment by bendiken** [comment]
@webdata How might we get the website updated? See also the related issue https://github.com/rdfhdt/hdt-java/issues/7

**Comment by webdata** [comment]
Sorry, the webpage is now updated!

**Comment by bendiken** [comment]
Thanks, @webdata!
