### ISSUE TITLE
Crash due to incorrect exception handling

### ISSUE THREAD

**Issue by JanWielemaker** [rdfhdt/hdt-cpp#48]
Using the latest master, trying to load `http://lod.labs.vu.nl/brt-clean.nt.gz` (be careful, almost 8Gb and you need to uncompress it before loading) we get SEGV in line 295 of FourSectionDictionary.cpp.  Here
we see `delete objects`.  

This is quite understandable as `objects` is possibly already deleted in the `try` section.   I'm not familiar enough with the code base to see the clean way out.

**Comment by webdata** [comment]
Hi @JanWielemaker, I fixed this issue in the last comment in the develop branch, https://github.com/rdfhdt/hdt-cpp/commit/0cd6693ab0a4519966981b09cda93d262f9464d2. I initialized the sections to NULL after deletion and also increased the number of bits of the pointers of the dictionary. I am able to generate your dataset http://lod.labs.vu.nl/brt-clean.nt.gz, but please confirm that it is working in order to close the issue.

**Comment by JanWielemaker** [comment]
Works!  FYI:

  - Input file: 73G ntriples
  - HDT file: 19G, took 3100 seconds to compile (intel E5-2630, plenty ram, ssd drives).
    Used close to 50G core at its peak.
  - Creating index took 3 min 14 sec, size 2.1G
  - Total 297,261,221 triples
