### ISSUE TITLE
Avoid allocation of strings in Dictionary::idToString.

### ISSUE THREAD

**Issue by vandenoever** [rdfhdt/hdt-cpp#52]
The Dictionary class has this function:
```virtual std::string idToString(unsigned int id, TripleComponentRole role)=0;```

Changing that to
```virtual void  idToString(unsigned int id, TripleComponentRole role, std::string& string);```
would allow the caller to supply an existing string object and avoid memory allocation.

**Comment by drobilla** [comment]
Modern compilers can usually elide copying in these scenarios, especially if the returned value is an unnamed temporary.  Unfortunately it's not here, but making it const may eliminate one copy.  There is always a big malloc and one copy here because of the design of CSD, this could be avoided easily enough and this copy eliminated but the API of CSD would need to change for that.

I implemented some straightforward fixes that should reduce string copying overhead (and generally improve const correctness) in https://github.com/rdfhdt/hdt-cpp/pull/80

**Comment by RubenVerborgh** [comment]
Following up in #80.

**Comment by LaurensRietveld** [comment]
I guess we can close this ticket?
