### ISSUE TITLE
Unicode/UTF-8 issue

### ISSUE THREAD

**Issue by kurzum** [rdfhdt/hdt-cpp#91]
Hi all,
I managed to convert DBpedia language versions to HDT with the CPP develop branch, see e.g. here:
http://downloads.dbpedia.org/2016-10/tmp/data/ja/

using this commit: https://github.com/rdfhdt/hdt-cpp/commit/b0bb66111b66c3b8ff2027fb886df39c18997717

The Ntriples are in unicode, which is fine according to the 1.1 spec. However, the unicode does not seem supported, below using the japanese version. 
So I wrote this with CPP and then read it with Java. Not sure where the incompatibility is. 

```
http://wikidata.dbpedia.org/resource/Q11178088 http://xmlns.com/foaf/0.1/name "������������"@ja
http://wikidata.dbpedia.org/resource/Q11178088 http://xmlns.com/foaf/0.1/name "������������������"@ja
http://wikidata.dbpedia.org/resource/Q11178276 http://dbpedia.org/ontology/address "������������������"@ja
```

**Comment by kurzum** [comment]
The gz file, which I used seems fine:
```
curl http://downloads.dbpedia.org/2016-10/tmp/data/ja/wkd_uris_selection.gz | gzip -dc
```

**Comment by wouterbeek** [comment]
Thanks for reporting!  I've created an HDT out of the file you link to, using hdt-cpp, and I have read it using hdt-cpp also, and then I do not see this issue.  The issue may only surface when reading with hdt-java.

**Comment by wouterbeek** [comment]
@kurzum I've installed hdt-java, and I also get the correct Unicode results there.

Can you try creating the HDT file anew using the develop branch of hdt-cpp?  There has been quite some changes WRT to parsing the input data (including a switch from Raptor to Serd as the main parser).  Also, can you make your HDT file available online so that I can open your file in hdt-java?

**Comment by kurzum** [comment]
@wouterbeek  the hdt file is also in the folder:
http://downloads.dbpedia.org/2016-10/tmp/data/ja/wkd_uris_selection.gz.hdt

as stated above, I was using this commit:
Commits on Aug 25, 2017
    @RubenVerborgh
    Remove RDFParserNtriples dependency from parser.
    RubenVerborgh committed 26 days ago
https://github.com/rdfhdt/hdt-cpp/commit/b0bb66111b66c3b8ff2027fb886df39c18997717

I tried updating it last week, but there was another problem when compiling (well it's the develop branch), so I used the version from 26 days ago. 

If you can't reproduce it, I will just try the latest commit

**Comment by kurzum** [comment]
I am already using the development branch using SERD and Libz .

**Comment by wouterbeek** [comment]
Thanks for making the HDT file available.  The file name [1] suggests that this is a gzipped HDT file (although the extension would normally be `.hdt.gz` in that case), however GNU zip complains when processing this file [2].  The file does also not seem to be an uncompressed HDT file, since opening it gives an error [3] (this specific error is given by the [Prolog/HDT API](https://github.com/JanWielemaker/hdt), but it is clear that the file cannot be opened by hdt-cpp).

```
[1] http://downloads.dbpedia.org/2016-10/tmp/data/ja/wkd_uris_selection.gz.hdt
[2] gzip: stdin: not in gzip format
[3] ERROR: HDT: Error trying to mmap HDT file
```

Can you check your HDT file again?  Maybe you can share the steps that you have used to generate the file, including potential compression steps.

PS: Feel free to open another issue in case you have an issue with compiling the latest commit on the development branch.

**Comment by kurzum** [comment]
@wouterbeek ok, I updated and recompiled with serd-0.28.0 
The hdt file is here: http://downloads.dbpedia.org/2016-10/tmp/data/ja/
it is 21MB larger now and has the proper unicode characters.... 

So this issue is fixed. I can't reproduce the compile error, it seems to be fixed as well. 

Another thing which I noticed is that serd stops parsing ntriples, if it finds an error. A better behaviour would be to ignore the broken triples or add a parser flag for strictness. I ran all files through rapper first to filter out the triples (I think rapper also has Unicode Normal Form issues, only accepting normal form c which is difficult for asian languages). 

Anyhow, this issue can be closed. 
@wouterbeek thanks. We actually didn't have time to talk to you at semantics.

**Comment by wouterbeek** [comment]
@kurzum Good to see that the latest development version solves the issue!

I have opened [an issue](https://github.com/drobilla/serd/issues/7) about adding robustness against syntax errors to Serd.

I don't know what the difference between Unicode with and without NFC is.  Is there an simple test case, preferably one triple, that we can use to test Serd and hdt-cpp for compliance?

SEMANTiCS was a bit too busy for me this year :(  Let's catch up at ISWC next month!
